# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fast_iterate_t_impl <- function(Y, df_j, nrep, thin, n, d, gamma, q, init, mu0, lambda0, alpha, beta) {
    .Call(`_autozyme_fast_iterate_t_impl`, Y, df_j, nrep, thin, n, d, gamma, q, init, mu0, lambda0, alpha, beta)
}

cpp_aggregate_triMean <- function(data, group_int, ngroups) {
    .Call(`_autozyme_cpp_aggregate_triMean`, data, group_int, ngroups)
}

cpp_aggregate_triMean_boot <- function(data, group_int, ngroups, permutation) {
    .Call(`_autozyme_cpp_aggregate_triMean_boot`, data, group_int, ngroups, permutation)
}

cpp_outer_Pnull <- function(dataLavg_T, dataRavg_T, agonist_T, antagonist_T, nLR, numCluster, Kh, n) {
    .Call(`_autozyme_cpp_outer_Pnull`, dataLavg_T, dataRavg_T, agonist_T, antagonist_T, nLR, numCluster, Kh, n)
}

cpp_unified_inner <- function(boot_tensor, ngenes, ngroups, nboot, Lflat, Loff, Rflat, Roff, coAflat, coAoff, coIflat, coIoff, agflat, agoff, antflat, antoff, Pnull_arr, nLR_active, Kh, n) {
    .Call(`_autozyme_cpp_unified_inner`, boot_tensor, ngenes, ngroups, nboot, Lflat, Loff, Rflat, Roff, coAflat, coAoff, coIflat, coIoff, agflat, agoff, antflat, antoff, Pnull_arr, nLR_active, Kh, n)
}

cpp_updateState <- function(eta_, mu_, mu_eta_val_, varmu_, dispersion, prior_sd_, x_aug_, x_nobs_, y_, weights_, offset_, prior_mean_, prior_scale_, prior_df_, family_idx, intercept, scaled) {
    .Call(`_autozyme_cpp_updateState`, eta_, mu_, mu_eta_val_, varmu_, dispersion, prior_sd_, x_aug_, x_nobs_, y_, weights_, offset_, prior_mean_, prior_scale_, prior_df_, family_idx, intercept, scaled)
}

fast_decontXEM_cpp <- function(counts, counts_colsums, theta, estimate_eta, eta, phi, z, estimate_delta, delta, pseudocount, n_threads_request) {
    .Call(`_autozyme_fast_decontXEM_cpp`, counts, counts_colsums, theta, estimate_eta, eta, phi, z, estimate_delta, delta, pseudocount, n_threads_request)
}

calcEsLeBatchCpp <- function(stats, selectedGenes, scoreType) {
    .Call(`_autozyme_calcEsLeBatchCpp`, stats, selectedGenes, scoreType)
}

fastFgseaMultilevelBatchCpp <- function(groupES, pathwaySizes, eps_per_group, ranks, sampleSize, seed, sign, nthreads = 0L) {
    .Call(`_autozyme_fastFgseaMultilevelBatchCpp`, groupES, pathwaySizes, eps_per_group, ranks, sampleSize, seed, sign, nthreads)
}

count_sum_by_group_dgc <- function(x_sexp, groups, ngroups) {
    .Call(`_autozyme_count_sum_by_group_dgc`, x_sexp, groups, ngroups)
}

portable_rank_dgc <- function(x, p, n_rows) {
    .Call(`_autozyme_portable_rank_dgc`, x, p, n_rows)
}

rank_sum_by_group_dgc <- function(x_sexp, groups, group_sizes) {
    .Call(`_autozyme_rank_sum_by_group_dgc`, x_sexp, groups, group_sizes)
}

omp_sum_nnz_expm1_groups <- function(sparse_mat, y, n_groups, n_threads = 0L) {
    .Call(`_autozyme_omp_sum_nnz_expm1_groups`, sparse_mat, y, n_groups, n_threads)
}

omp_filter_pct_lfc <- function(nnz_mat, expm1_sums, total_nnz, total_expm1, cluster_sizes, sizes_rest, valid_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, log_base, n_threads = 0L) {
    .Call(`_autozyme_omp_filter_pct_lfc`, nnz_mat, expm1_sums, total_nnz, total_expm1, cluster_sizes, sizes_rest, valid_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, log_base, n_threads)
}

omp_subset_transpose_rank_pval <- function(data_layer, union_idx, y, n_groups, cluster_sizes, n_threads = 0L) {
    .Call(`_autozyme_omp_subset_transpose_rank_pval`, data_layer, union_idx, y, n_groups, cluster_sizes, n_threads)
}

omp_rank_ustat_pval <- function(sparse_mat, y, n_groups, cluster_sizes, n_threads = 0L) {
    .Call(`_autozyme_omp_rank_ustat_pval`, sparse_mat, y, n_groups, cluster_sizes, n_threads)
}

fast_smooth_window_cpp <- function(data, window_length) {
    .Call(`_autozyme_fast_smooth_window_cpp`, data, window_length)
}

fast_smooth_long_chromosomes_cpp <- function(data, starts, lens, window_length) {
    .Call(`_autozyme_fast_smooth_long_chromosomes_cpp`, data, starts, lens, window_length)
}

fast_scale_columns_cpp <- function(data, scales) {
    .Call(`_autozyme_fast_scale_columns_cpp`, data, scales)
}

fast_log1p_scale_cpp <- function(expr, inv_ln2) {
    .Call(`_autozyme_fast_log1p_scale_cpp`, expr, inv_ln2)
}

fast_invert_log2_cpp <- function(expr, ln2) {
    .Call(`_autozyme_fast_invert_log2_cpp`, expr, ln2)
}

fast_center_columns_cpp <- function(expr, centers) {
    .Call(`_autozyme_fast_center_columns_cpp`, expr, centers)
}

fast_subtract_ref_bounds_cpp <- function(expr, ref_groups, use_bounds, threshold, do_threshold) {
    .Call(`_autozyme_fast_subtract_ref_bounds_cpp`, expr, ref_groups, use_bounds, threshold, do_threshold)
}

fast_apply_dropout_cpp <- function(counts, padj) {
    .Call(`_autozyme_fast_apply_dropout_cpp`, counts, padj)
}

fast_state_consensus_cpp <- function(mat) {
    .Call(`_autozyme_fast_state_consensus_cpp`, mat)
}

fast_cell_prob_cpp <- function(epsilons, nstates) {
    .Call(`_autozyme_fast_cell_prob_cpp`, epsilons, nstates)
}

fast_viterbi_adj_cpp <- function(x, Pi, delta, means, sds) {
    .Call(`_autozyme_fast_viterbi_adj_cpp`, x, Pi, delta, means, sds)
}

zyme_fill_dcast <- function(row_codes, col_codes, counts, n_rows, n_cols) {
    .Call(`_autozyme_zyme_fill_dcast`, row_codes, col_codes, counts, n_rows, n_cols)
}

az_blas_gemm <- function(A, B, transA = FALSE, transB = FALSE, threads = 0L, dll_paths = character()) {
    .Call(`_autozyme_az_blas_gemm`, A, B, transA, transB, threads, dll_paths)
}

az_blas_crossprod <- function(X, threads = 0L, dll_paths = character()) {
    .Call(`_autozyme_az_blas_crossprod`, X, threads, dll_paths)
}

az_blas_info <- function(dll_paths = character()) {
    .Call(`_autozyme_az_blas_info`, dll_paths)
}

native_pca_available <- function() {
    .Call(`_autozyme_native_pca_available`)
}

native_pca_run <- function(X, npcs, weight_by_var = TRUE) {
    .Call(`_autozyme_native_pca_run`, X, npcs, weight_by_var)
}

native_cca_formA <- function(X1, X2) {
    .Call(`_autozyme_native_cca_formA`, X1, X2)
}

native_matmul <- function(A, B) {
    .Call(`_autozyme_native_matmul`, A, B)
}

rctd_cpp_row_idx1 <- function(y, k_val) {
    .Call(`_autozyme_rctd_cpp_row_idx1`, y, k_val)
}

rctd_cpp_row_idx_mat <- function(y, k_val) {
    .Call(`_autozyme_rctd_cpp_row_idx_mat`, y, k_val)
}

rctd_cpp_calc_log_l_sum <- function(lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_calc_log_l_sum`, lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_calc_log_l_vec <- function(lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_calc_log_l_vec`, lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_get_d1_d2 <- function(y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_get_d1_d2`, y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_get_der_fast_nonbulk <- function(s, y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_get_der_fast_nonbulk`, s, y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_solve_wls_p1 <- function(s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_solve_wls_p1`, s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_solve_wls_p2 <- function(s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_solve_wls_p2`, s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_irwls_sparse_p12 <- function(s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_irwls_sparse_p12`, s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_irwls_full_nonbulk <- function(s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_irwls_full_nonbulk`, s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_score_sparse_candidates <- function(profiles, y, candidate_cols, row_idx_in, n_umi, min_change, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_score_sparse_candidates`, profiles, y, candidate_cols, row_idx_in, n_umi, min_change, q_mat, sq_mat, x_vals, k_val)
}

rctd_cpp_fit_sparse_pair <- function(profiles, y, pair_cols, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val) {
    .Call(`_autozyme_rctd_cpp_fit_sparse_pair`, profiles, y, pair_cols, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val)
}

score_ligands_cpp <- function(mat, pos_row_idx, neg_row_idx, col_idx, threads) {
    .Call(`_autozyme_score_ligands_cpp`, mat, pos_row_idx, neg_row_idx, col_idx, threads)
}

fast_lr_outer_triplets_cpp <- function(a, b) {
    .Call(`_autozyme_fast_lr_outer_triplets_cpp`, a, b)
}

turbo_all_in_one_wilcox <- function(x, p, i, ncol_orig, nrow_orig, groups, ngroups) {
    .Call(`_autozyme_turbo_all_in_one_wilcox`, x, p, i, ncol_orig, nrow_orig, groups, ngroups)
}

parallel_all_in_one_dgc <- function(x_sexp, groups, group_sizes) {
    .Call(`_autozyme_parallel_all_in_one_dgc`, x_sexp, groups, group_sizes)
}

turbo_annoy_build_search <- function(data, k, n_trees, n_threads) {
    .Call(`_autozyme_turbo_annoy_build_search`, data, k, n_trees, n_threads)
}

seurat_log_normalize_dgc <- function(mat, scale_factor, grain_size = 100L) {
    invisible(.Call(`_autozyme_seurat_log_normalize_dgc`, mat, scale_factor, grain_size))
}

turbo_scale_sparse_full <- function(sparse_mat, gene_indices, scale_max) {
    .Call(`_autozyme_turbo_scale_sparse_full`, sparse_mat, gene_indices, scale_max)
}

turbo_csc_to_csr <- function(csc_i, csc_p, csc_x, nrow, ncol) {
    .Call(`_autozyme_turbo_csc_to_csr`, csc_i, csc_p, csc_x, nrow, ncol)
}

turbo_stats_correct_sparse <- function(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, corr_factor, min_var, clip_lo, clip_hi, do_correct) {
    .Call(`_autozyme_turbo_stats_correct_sparse`, intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, corr_factor, min_var, clip_lo, clip_hi, do_correct)
}

turbo_fused_resid_center_sparse <- function(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, min_var, wide_clip_lo, wide_clip_hi, narrow_clip_lo, narrow_clip_hi) {
    .Call(`_autozyme_turbo_fused_resid_center_sparse`, intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, min_var, wide_clip_lo, wide_clip_hi, narrow_clip_lo, narrow_clip_hi)
}

turbo_FastSparseRowMeanVar <- function(p, i, x, nrow, ncol) {
    .Call(`_autozyme_turbo_FastSparseRowMeanVar`, p, i, x, nrow, ncol)
}

turbo_FastSparseRowVarStd <- function(p, i, x, nrow, ncol, mu, sd, vmax, nnzPerRow) {
    .Call(`_autozyme_turbo_FastSparseRowVarStd`, p, i, x, nrow, ncol, mu, sd, vmax, nnzPerRow)
}

az_dgc_row_stats_cpp <- function(x_sexp, detected_threshold = 0.0) {
    .Call(`_autozyme_az_dgc_row_stats_cpp`, x_sexp, detected_threshold)
}

az_dgc_group_summary_cpp <- function(x_sexp, groups, ngroups, detected_threshold = 0.0) {
    .Call(`_autozyme_az_dgc_group_summary_cpp`, x_sexp, groups, ngroups, detected_threshold)
}

az_dense_group_summary_cpp <- function(x, groups, ngroups, detected_threshold = 0.0, na_rm = FALSE) {
    .Call(`_autozyme_az_dense_group_summary_cpp`, x, groups, ngroups, detected_threshold, na_rm)
}

zyme_soft_assignment <- function(X, C, sigma) {
    .Call(`_autozyme_zyme_soft_assignment`, X, C, sigma)
}

nb_Dd_cpp <- function(y, mu, theta_log, wt, level) {
    .Call(`_autozyme_nb_Dd_cpp`, y, mu, theta_log, wt, level)
}

nb_dDeta_log_cpp <- function(y, mu, wt, theta_log, deriv) {
    .Call(`_autozyme_nb_dDeta_log_cpp`, y, mu, wt, theta_log, deriv)
}

linkinv_log_cpp <- function(eta) {
    .Call(`_autozyme_linkinv_log_cpp`, eta)
}

nb_dev_resids_cpp <- function(y, mu, wt, theta_log) {
    .Call(`_autozyme_nb_dev_resids_cpp`, y, mu, wt, theta_log)
}

nb_ls_cpp <- function(y, w, theta_log, scale) {
    .Call(`_autozyme_nb_ls_cpp`, y, w, theta_log, scale)
}

accelerate_crossprod <- function(X) {
    .Call(`_autozyme_accelerate_crossprod`, X)
}

