// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_iterate_t_impl
List fast_iterate_t_impl(const arma::mat& Y, const List& df_j, int nrep, int thin, int n, int d, double gamma, int q, const arma::uvec& init, const NumericVector& mu0, const arma::mat& lambda0, double alpha, double beta);
RcppExport SEXP _autozyme_fast_iterate_t_impl(SEXP YSEXP, SEXP df_jSEXP, SEXP nrepSEXP, SEXP thinSEXP, SEXP nSEXP, SEXP dSEXP, SEXP gammaSEXP, SEXP qSEXP, SEXP initSEXP, SEXP mu0SEXP, SEXP lambda0SEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const List& >::type df_j(df_jSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type q(qSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type init(initSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type lambda0(lambda0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_iterate_t_impl(Y, df_j, nrep, thin, n, d, gamma, q, init, mu0, lambda0, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}
// cpp_aggregate_triMean
NumericMatrix cpp_aggregate_triMean(NumericMatrix data, IntegerVector group_int, int ngroups);
RcppExport SEXP _autozyme_cpp_aggregate_triMean(SEXP dataSEXP, SEXP group_intSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_int(group_intSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_aggregate_triMean(data, group_int, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// cpp_aggregate_triMean_boot
NumericVector cpp_aggregate_triMean_boot(NumericMatrix data, IntegerVector group_int, int ngroups, IntegerMatrix permutation);
RcppExport SEXP _autozyme_cpp_aggregate_triMean_boot(SEXP dataSEXP, SEXP group_intSEXP, SEXP ngroupsSEXP, SEXP permutationSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_int(group_intSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type permutation(permutationSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_aggregate_triMean_boot(data, group_int, ngroups, permutation));
    return rcpp_result_gen;
END_RCPP
}
// cpp_outer_Pnull
NumericVector cpp_outer_Pnull(NumericMatrix dataLavg_T, /* numCluster × nLR */     NumericMatrix dataRavg_T, /* numCluster × nLR */     NumericMatrix agonist_T, /* numCluster × nLR (ones if not agonist) */     NumericMatrix antagonist_T, /* numCluster × nLR (ones if not antagonist) */     int nLR, int numCluster, double Kh, double n);
RcppExport SEXP _autozyme_cpp_outer_Pnull(SEXP dataLavg_TSEXP, SEXP dataRavg_TSEXP, SEXP agonist_TSEXP, SEXP antagonist_TSEXP, SEXP nLRSEXP, SEXP numClusterSEXP, SEXP KhSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type dataLavg_T(dataLavg_TSEXP);
    Rcpp::traits::input_parameter< /* numCluster × nLR */     NumericMatrix >::type dataRavg_T(dataRavg_TSEXP);
    Rcpp::traits::input_parameter< /* numCluster × nLR */     NumericMatrix >::type agonist_T(agonist_TSEXP);
    Rcpp::traits::input_parameter< /* numCluster × nLR (ones if not agonist) */     NumericMatrix >::type antagonist_T(antagonist_TSEXP);
    Rcpp::traits::input_parameter< /* numCluster × nLR (ones if not antagonist) */     int >::type nLR(nLRSEXP);
    Rcpp::traits::input_parameter< int >::type numCluster(numClusterSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_outer_Pnull(dataLavg_T, dataRavg_T, agonist_T, antagonist_T, nLR, numCluster, Kh, n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_unified_inner
NumericVector cpp_unified_inner(NumericVector boot_tensor, int ngenes, int ngroups, int nboot, IntegerVector Lflat, IntegerVector Loff, IntegerVector Rflat, IntegerVector Roff, IntegerVector coAflat, IntegerVector coAoff, IntegerVector coIflat, IntegerVector coIoff, IntegerVector agflat, IntegerVector agoff, IntegerVector antflat, IntegerVector antoff, NumericVector Pnull_arr, int nLR_active, double Kh, double n);
RcppExport SEXP _autozyme_cpp_unified_inner(SEXP boot_tensorSEXP, SEXP ngenesSEXP, SEXP ngroupsSEXP, SEXP nbootSEXP, SEXP LflatSEXP, SEXP LoffSEXP, SEXP RflatSEXP, SEXP RoffSEXP, SEXP coAflatSEXP, SEXP coAoffSEXP, SEXP coIflatSEXP, SEXP coIoffSEXP, SEXP agflatSEXP, SEXP agoffSEXP, SEXP antflatSEXP, SEXP antoffSEXP, SEXP Pnull_arrSEXP, SEXP nLR_activeSEXP, SEXP KhSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type boot_tensor(boot_tensorSEXP);
    Rcpp::traits::input_parameter< int >::type ngenes(ngenesSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Lflat(LflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Loff(LoffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Rflat(RflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Roff(RoffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type coAflat(coAflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type coAoff(coAoffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type coIflat(coIflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type coIoff(coIoffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type agflat(agflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type agoff(agoffSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type antflat(antflatSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type antoff(antoffSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Pnull_arr(Pnull_arrSEXP);
    Rcpp::traits::input_parameter< int >::type nLR_active(nLR_activeSEXP);
    Rcpp::traits::input_parameter< double >::type Kh(KhSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_unified_inner(boot_tensor, ngenes, ngroups, nboot, Lflat, Loff, Rflat, Roff, coAflat, coAoff, coIflat, coIoff, agflat, agoff, antflat, antoff, Pnull_arr, nLR_active, Kh, n));
    return rcpp_result_gen;
END_RCPP
}
// cpp_updateState
List cpp_updateState(NumericVector eta_, NumericVector mu_, NumericVector mu_eta_val_, NumericVector varmu_, double dispersion, NumericVector prior_sd_, NumericMatrix x_aug_, NumericMatrix x_nobs_, NumericVector y_, NumericVector weights_, NumericVector offset_, NumericVector prior_mean_, NumericVector prior_scale_, NumericVector prior_df_, int family_idx, int intercept, int scaled);
RcppExport SEXP _autozyme_cpp_updateState(SEXP eta_SEXP, SEXP mu_SEXP, SEXP mu_eta_val_SEXP, SEXP varmu_SEXP, SEXP dispersionSEXP, SEXP prior_sd_SEXP, SEXP x_aug_SEXP, SEXP x_nobs_SEXP, SEXP y_SEXP, SEXP weights_SEXP, SEXP offset_SEXP, SEXP prior_mean_SEXP, SEXP prior_scale_SEXP, SEXP prior_df_SEXP, SEXP family_idxSEXP, SEXP interceptSEXP, SEXP scaledSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta_(eta_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_eta_val_(mu_eta_val_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type varmu_(varmu_SEXP);
    Rcpp::traits::input_parameter< double >::type dispersion(dispersionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_sd_(prior_sd_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_aug_(x_aug_SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_nobs_(x_nobs_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights_(weights_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset_(offset_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_mean_(prior_mean_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_scale_(prior_scale_SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_df_(prior_df_SEXP);
    Rcpp::traits::input_parameter< int >::type family_idx(family_idxSEXP);
    Rcpp::traits::input_parameter< int >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< int >::type scaled(scaledSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_updateState(eta_, mu_, mu_eta_val_, varmu_, dispersion, prior_sd_, x_aug_, x_nobs_, y_, weights_, offset_, prior_mean_, prior_scale_, prior_df_, family_idx, intercept, scaled));
    return rcpp_result_gen;
END_RCPP
}
// fast_decontXEM_cpp
List fast_decontXEM_cpp(const Eigen::MappedSparseMatrix<double>& counts, const NumericVector& counts_colsums, const NumericVector& theta, const bool estimate_eta, const NumericMatrix& eta, const NumericMatrix& phi, const IntegerVector& z, const bool estimate_delta, const NumericVector& delta, const double pseudocount, const int n_threads_request);
RcppExport SEXP _autozyme_fast_decontXEM_cpp(SEXP countsSEXP, SEXP counts_colsumsSEXP, SEXP thetaSEXP, SEXP estimate_etaSEXP, SEXP etaSEXP, SEXP phiSEXP, SEXP zSEXP, SEXP estimate_deltaSEXP, SEXP deltaSEXP, SEXP pseudocountSEXP, SEXP n_threads_requestSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MappedSparseMatrix<double>& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type counts_colsums(counts_colsumsSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const bool >::type estimate_eta(estimate_etaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const bool >::type estimate_delta(estimate_deltaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const double >::type pseudocount(pseudocountSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads_request(n_threads_requestSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_decontXEM_cpp(counts, counts_colsums, theta, estimate_eta, eta, phi, z, estimate_delta, delta, pseudocount, n_threads_request));
    return rcpp_result_gen;
END_RCPP
}
// fitDisp_zyme
List fitDisp_zyme(SEXP ySEXP, SEXP xSEXP, SEXP mu_hatSEXP, SEXP log_alphaSEXP, SEXP log_alpha_prior_meanSEXP, SEXP log_alpha_prior_sigmasqSEXP, SEXP min_log_alphaSEXP, SEXP kappa_0SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP usePriorSEXP, SEXP weightsSEXP, SEXP useWeightsSEXP, SEXP weightThresholdSEXP, SEXP useCRSEXP);
RcppExport SEXP _autozyme_fitDisp_zyme(SEXP ySEXPSEXP, SEXP xSEXPSEXP, SEXP mu_hatSEXPSEXP, SEXP log_alphaSEXPSEXP, SEXP log_alpha_prior_meanSEXPSEXP, SEXP log_alpha_prior_sigmasqSEXPSEXP, SEXP min_log_alphaSEXPSEXP, SEXP kappa_0SEXPSEXP, SEXP tolSEXPSEXP, SEXP maxitSEXPSEXP, SEXP usePriorSEXPSEXP, SEXP weightsSEXPSEXP, SEXP useWeightsSEXPSEXP, SEXP weightThresholdSEXPSEXP, SEXP useCRSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xSEXP(xSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type mu_hatSEXP(mu_hatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type log_alphaSEXP(log_alphaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type log_alpha_prior_meanSEXP(log_alpha_prior_meanSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type log_alpha_prior_sigmasqSEXP(log_alpha_prior_sigmasqSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min_log_alphaSEXP(min_log_alphaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type kappa_0SEXP(kappa_0SEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolSEXP(tolSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxitSEXP(maxitSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type usePriorSEXP(usePriorSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weightsSEXP(weightsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type useWeightsSEXP(useWeightsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weightThresholdSEXP(weightThresholdSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type useCRSEXP(useCRSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(fitDisp_zyme(ySEXP, xSEXP, mu_hatSEXP, log_alphaSEXP, log_alpha_prior_meanSEXP, log_alpha_prior_sigmasqSEXP, min_log_alphaSEXP, kappa_0SEXP, tolSEXP, maxitSEXP, usePriorSEXP, weightsSEXP, useWeightsSEXP, weightThresholdSEXP, useCRSEXP));
    return rcpp_result_gen;
END_RCPP
}
// row_trimmed_means
NumericVector row_trimmed_means(NumericMatrix m, IntegerVector cols0, double trim);
RcppExport SEXP _autozyme_row_trimmed_means(SEXP mSEXP, SEXP cols0SEXP, SEXP trimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cols0(cols0SEXP);
    Rcpp::traits::input_parameter< double >::type trim(trimSEXP);
    rcpp_result_gen = Rcpp::wrap(row_trimmed_means(m, cols0, trim));
    return rcpp_result_gen;
END_RCPP
}
// fitBeta_zyme
List fitBeta_zyme(SEXP ySEXP, SEXP xSEXP, SEXP nfSEXP, SEXP alpha_hatSEXP, SEXP contrastSEXP, SEXP beta_matSEXP, SEXP lambdaSEXP, SEXP weightsSEXP, SEXP useWeightsSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP useQRSEXP, SEXP minmuSEXP);
RcppExport SEXP _autozyme_fitBeta_zyme(SEXP ySEXPSEXP, SEXP xSEXPSEXP, SEXP nfSEXPSEXP, SEXP alpha_hatSEXPSEXP, SEXP contrastSEXPSEXP, SEXP beta_matSEXPSEXP, SEXP lambdaSEXPSEXP, SEXP weightsSEXPSEXP, SEXP useWeightsSEXPSEXP, SEXP tolSEXPSEXP, SEXP maxitSEXPSEXP, SEXP useQRSEXPSEXP, SEXP minmuSEXPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ySEXP(ySEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type xSEXP(xSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nfSEXP(nfSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type alpha_hatSEXP(alpha_hatSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type contrastSEXP(contrastSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type beta_matSEXP(beta_matSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type lambdaSEXP(lambdaSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type weightsSEXP(weightsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type useWeightsSEXP(useWeightsSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolSEXP(tolSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type maxitSEXP(maxitSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type useQRSEXP(useQRSEXPSEXP);
    Rcpp::traits::input_parameter< SEXP >::type minmuSEXP(minmuSEXPSEXP);
    rcpp_result_gen = Rcpp::wrap(fitBeta_zyme(ySEXP, xSEXP, nfSEXP, alpha_hatSEXP, contrastSEXP, beta_matSEXP, lambdaSEXP, weightsSEXP, useWeightsSEXP, tolSEXP, maxitSEXP, useQRSEXP, minmuSEXP));
    return rcpp_result_gen;
END_RCPP
}
// fastgam_fit
Rcpp::List fastgam_fit(const arma::mat& Xr, const arma::mat& Sr, const arma::vec& offset, const arma::mat& Y, double rankS, double logdetSpos, double MpEff, double start_llam, double start_lth, int nthreads);
RcppExport SEXP _autozyme_fastgam_fit(SEXP XrSEXP, SEXP SrSEXP, SEXP offsetSEXP, SEXP YSEXP, SEXP rankSSEXP, SEXP logdetSposSEXP, SEXP MpEffSEXP, SEXP start_llamSEXP, SEXP start_lthSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Sr(SrSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< double >::type rankS(rankSSEXP);
    Rcpp::traits::input_parameter< double >::type logdetSpos(logdetSposSEXP);
    Rcpp::traits::input_parameter< double >::type MpEff(MpEffSEXP);
    Rcpp::traits::input_parameter< double >::type start_llam(start_llamSEXP);
    Rcpp::traits::input_parameter< double >::type start_lth(start_lthSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastgam_fit(Xr, Sr, offset, Y, rankS, logdetSpos, MpEff, start_llam, start_lth, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// calcEsLeBatchCpp
Rcpp::List calcEsLeBatchCpp(Rcpp::NumericVector const& stats, Rcpp::List const& selectedGenes, std::string scoreType);
RcppExport SEXP _autozyme_calcEsLeBatchCpp(SEXP statsSEXP, SEXP selectedGenesSEXP, SEXP scoreTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector const& >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List const& >::type selectedGenes(selectedGenesSEXP);
    Rcpp::traits::input_parameter< std::string >::type scoreType(scoreTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(calcEsLeBatchCpp(stats, selectedGenes, scoreType));
    return rcpp_result_gen;
END_RCPP
}
// fastFgseaMultilevelBatchCpp
Rcpp::List fastFgseaMultilevelBatchCpp(Rcpp::List groupES, Rcpp::IntegerVector pathwaySizes, Rcpp::NumericVector eps_per_group, const Rcpp::NumericVector& ranks, int sampleSize, int seed, bool sign, int nthreads);
RcppExport SEXP _autozyme_fastFgseaMultilevelBatchCpp(SEXP groupESSEXP, SEXP pathwaySizesSEXP, SEXP eps_per_groupSEXP, SEXP ranksSEXP, SEXP sampleSizeSEXP, SEXP seedSEXP, SEXP signSEXP, SEXP nthreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type groupES(groupESSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type pathwaySizes(pathwaySizesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eps_per_group(eps_per_groupSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ranks(ranksSEXP);
    Rcpp::traits::input_parameter< int >::type sampleSize(sampleSizeSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< bool >::type sign(signSEXP);
    Rcpp::traits::input_parameter< int >::type nthreads(nthreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastFgseaMultilevelBatchCpp(groupES, pathwaySizes, eps_per_group, ranks, sampleSize, seed, sign, nthreads));
    return rcpp_result_gen;
END_RCPP
}
// count_sum_by_group_dgc
List count_sum_by_group_dgc(SEXP x_sexp, IntegerVector groups, int ngroups);
RcppExport SEXP _autozyme_count_sum_by_group_dgc(SEXP x_sexpSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_sum_by_group_dgc(x_sexp, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// portable_rank_dgc
List portable_rank_dgc(NumericVector x, IntegerVector p, int n_rows);
RcppExport SEXP _autozyme_portable_rank_dgc(SEXP xSEXP, SEXP pSEXP, SEXP n_rowsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    rcpp_result_gen = Rcpp::wrap(portable_rank_dgc(x, p, n_rows));
    return rcpp_result_gen;
END_RCPP
}
// rank_sum_by_group_dgc
NumericMatrix rank_sum_by_group_dgc(SEXP x_sexp, IntegerVector groups, IntegerVector group_sizes);
RcppExport SEXP _autozyme_rank_sum_by_group_dgc(SEXP x_sexpSEXP, SEXP groupsSEXP, SEXP group_sizesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_sizes(group_sizesSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_sum_by_group_dgc(x_sexp, groups, group_sizes));
    return rcpp_result_gen;
END_RCPP
}
// omp_sum_nnz_expm1_groups
List omp_sum_nnz_expm1_groups(S4 sparse_mat, IntegerVector y, int n_groups, int n_threads);
RcppExport SEXP _autozyme_omp_sum_nnz_expm1_groups(SEXP sparse_matSEXP, SEXP ySEXP, SEXP n_groupsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sparse_mat(sparse_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(omp_sum_nnz_expm1_groups(sparse_mat, y, n_groups, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// omp_filter_pct_lfc
List omp_filter_pct_lfc(NumericMatrix nnz_mat, NumericMatrix expm1_sums, NumericVector total_nnz, NumericVector total_expm1, NumericVector cluster_sizes, NumericVector sizes_rest, LogicalVector valid_mask, double min_pct, double min_diff_pct, double logfc_threshold, bool only_pos, double log_base, int n_threads);
RcppExport SEXP _autozyme_omp_filter_pct_lfc(SEXP nnz_matSEXP, SEXP expm1_sumsSEXP, SEXP total_nnzSEXP, SEXP total_expm1SEXP, SEXP cluster_sizesSEXP, SEXP sizes_restSEXP, SEXP valid_maskSEXP, SEXP min_pctSEXP, SEXP min_diff_pctSEXP, SEXP logfc_thresholdSEXP, SEXP only_posSEXP, SEXP log_baseSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type nnz_mat(nnz_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type expm1_sums(expm1_sumsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type total_nnz(total_nnzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type total_expm1(total_expm1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cluster_sizes(cluster_sizesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sizes_rest(sizes_restSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type valid_mask(valid_maskSEXP);
    Rcpp::traits::input_parameter< double >::type min_pct(min_pctSEXP);
    Rcpp::traits::input_parameter< double >::type min_diff_pct(min_diff_pctSEXP);
    Rcpp::traits::input_parameter< double >::type logfc_threshold(logfc_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type only_pos(only_posSEXP);
    Rcpp::traits::input_parameter< double >::type log_base(log_baseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(omp_filter_pct_lfc(nnz_mat, expm1_sums, total_nnz, total_expm1, cluster_sizes, sizes_rest, valid_mask, min_pct, min_diff_pct, logfc_threshold, only_pos, log_base, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// omp_subset_transpose_rank_pval
NumericMatrix omp_subset_transpose_rank_pval(S4 data_layer, IntegerVector union_idx, IntegerVector y, int n_groups, NumericVector cluster_sizes, int n_threads);
RcppExport SEXP _autozyme_omp_subset_transpose_rank_pval(SEXP data_layerSEXP, SEXP union_idxSEXP, SEXP ySEXP, SEXP n_groupsSEXP, SEXP cluster_sizesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type data_layer(data_layerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type union_idx(union_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cluster_sizes(cluster_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(omp_subset_transpose_rank_pval(data_layer, union_idx, y, n_groups, cluster_sizes, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// omp_rank_ustat_pval
NumericMatrix omp_rank_ustat_pval(S4 sparse_mat, IntegerVector y, int n_groups, NumericVector cluster_sizes, int n_threads);
RcppExport SEXP _autozyme_omp_rank_ustat_pval(SEXP sparse_matSEXP, SEXP ySEXP, SEXP n_groupsSEXP, SEXP cluster_sizesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sparse_mat(sparse_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cluster_sizes(cluster_sizesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(omp_rank_ustat_pval(sparse_mat, y, n_groups, cluster_sizes, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_smooth_window_cpp
Rcpp::NumericMatrix fast_smooth_window_cpp(Rcpp::NumericMatrix data, int window_length);
RcppExport SEXP _autozyme_fast_smooth_window_cpp(SEXP dataSEXP, SEXP window_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type window_length(window_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_smooth_window_cpp(data, window_length));
    return rcpp_result_gen;
END_RCPP
}
// fast_smooth_long_chromosomes_cpp
Rcpp::NumericMatrix fast_smooth_long_chromosomes_cpp(Rcpp::NumericMatrix data, Rcpp::IntegerVector starts, Rcpp::IntegerVector lens, int window_length);
RcppExport SEXP _autozyme_fast_smooth_long_chromosomes_cpp(SEXP dataSEXP, SEXP startsSEXP, SEXP lensSEXP, SEXP window_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type starts(startsSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type lens(lensSEXP);
    Rcpp::traits::input_parameter< int >::type window_length(window_lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_smooth_long_chromosomes_cpp(data, starts, lens, window_length));
    return rcpp_result_gen;
END_RCPP
}
// fast_scale_columns_cpp
Rcpp::NumericMatrix fast_scale_columns_cpp(Rcpp::NumericMatrix data, Rcpp::NumericVector scales);
RcppExport SEXP _autozyme_fast_scale_columns_cpp(SEXP dataSEXP, SEXP scalesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type scales(scalesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_scale_columns_cpp(data, scales));
    return rcpp_result_gen;
END_RCPP
}
// fast_log1p_scale_cpp
Rcpp::NumericMatrix fast_log1p_scale_cpp(Rcpp::NumericMatrix expr, double inv_ln2);
RcppExport SEXP _autozyme_fast_log1p_scale_cpp(SEXP exprSEXP, SEXP inv_ln2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< double >::type inv_ln2(inv_ln2SEXP);
    rcpp_result_gen = Rcpp::wrap(fast_log1p_scale_cpp(expr, inv_ln2));
    return rcpp_result_gen;
END_RCPP
}
// fast_invert_log2_cpp
Rcpp::NumericMatrix fast_invert_log2_cpp(Rcpp::NumericMatrix expr, double ln2);
RcppExport SEXP _autozyme_fast_invert_log2_cpp(SEXP exprSEXP, SEXP ln2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< double >::type ln2(ln2SEXP);
    rcpp_result_gen = Rcpp::wrap(fast_invert_log2_cpp(expr, ln2));
    return rcpp_result_gen;
END_RCPP
}
// fast_center_columns_cpp
Rcpp::NumericMatrix fast_center_columns_cpp(Rcpp::NumericMatrix expr, Rcpp::NumericVector centers);
RcppExport SEXP _autozyme_fast_center_columns_cpp(SEXP exprSEXP, SEXP centersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type centers(centersSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_center_columns_cpp(expr, centers));
    return rcpp_result_gen;
END_RCPP
}
// fast_subtract_ref_bounds_cpp
Rcpp::NumericMatrix fast_subtract_ref_bounds_cpp(Rcpp::NumericMatrix expr, Rcpp::List ref_groups, bool use_bounds, double threshold, bool do_threshold);
RcppExport SEXP _autozyme_fast_subtract_ref_bounds_cpp(SEXP exprSEXP, SEXP ref_groupsSEXP, SEXP use_boundsSEXP, SEXP thresholdSEXP, SEXP do_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type expr(exprSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type ref_groups(ref_groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_bounds(use_boundsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type do_threshold(do_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_subtract_ref_bounds_cpp(expr, ref_groups, use_bounds, threshold, do_threshold));
    return rcpp_result_gen;
END_RCPP
}
// fast_apply_dropout_cpp
Rcpp::NumericMatrix fast_apply_dropout_cpp(Rcpp::NumericMatrix counts, Rcpp::NumericVector padj);
RcppExport SEXP _autozyme_fast_apply_dropout_cpp(SEXP countsSEXP, SEXP padjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type padj(padjSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_apply_dropout_cpp(counts, padj));
    return rcpp_result_gen;
END_RCPP
}
// fast_state_consensus_cpp
Rcpp::NumericVector fast_state_consensus_cpp(Rcpp::NumericMatrix mat);
RcppExport SEXP _autozyme_fast_state_consensus_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_state_consensus_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// fast_cell_prob_cpp
Rcpp::NumericMatrix fast_cell_prob_cpp(Rcpp::NumericMatrix epsilons, int nstates);
RcppExport SEXP _autozyme_fast_cell_prob_cpp(SEXP epsilonsSEXP, SEXP nstatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type epsilons(epsilonsSEXP);
    Rcpp::traits::input_parameter< int >::type nstates(nstatesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_cell_prob_cpp(epsilons, nstates));
    return rcpp_result_gen;
END_RCPP
}
// fast_viterbi_adj_cpp
Rcpp::NumericVector fast_viterbi_adj_cpp(Rcpp::NumericVector x, Rcpp::NumericMatrix Pi, Rcpp::NumericVector delta, Rcpp::NumericVector means, Rcpp::NumericVector sds);
RcppExport SEXP _autozyme_fast_viterbi_adj_cpp(SEXP xSEXP, SEXP PiSEXP, SEXP deltaSEXP, SEXP meansSEXP, SEXP sdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Pi(PiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sds(sdsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_viterbi_adj_cpp(x, Pi, delta, means, sds));
    return rcpp_result_gen;
END_RCPP
}
// zyme_fill_dcast
IntegerMatrix zyme_fill_dcast(IntegerVector row_codes, IntegerVector col_codes, IntegerVector counts, int n_rows, int n_cols);
RcppExport SEXP _autozyme_zyme_fill_dcast(SEXP row_codesSEXP, SEXP col_codesSEXP, SEXP countsSEXP, SEXP n_rowsSEXP, SEXP n_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type row_codes(row_codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_codes(col_codesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type n_rows(n_rowsSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(zyme_fill_dcast(row_codes, col_codes, counts, n_rows, n_cols));
    return rcpp_result_gen;
END_RCPP
}
// fast_milor_pdist_one
S4 fast_milor_pdist_one(NumericMatrix in_x, SEXP row_names);
RcppExport SEXP _autozyme_fast_milor_pdist_one(SEXP in_xSEXP, SEXP row_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type in_x(in_xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type row_names(row_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_milor_pdist_one(in_x, row_names));
    return rcpp_result_gen;
END_RCPP
}
// fast_milor_pdist_batch
List fast_milor_pdist_batch(NumericMatrix rd_mat, IntegerMatrix non_zero, int nh_n, SEXP cell_names, int n_threads);
RcppExport SEXP _autozyme_fast_milor_pdist_batch(SEXP rd_matSEXP, SEXP non_zeroSEXP, SEXP nh_nSEXP, SEXP cell_namesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type rd_mat(rd_matSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type non_zero(non_zeroSEXP);
    Rcpp::traits::input_parameter< int >::type nh_n(nh_nSEXP);
    Rcpp::traits::input_parameter< SEXP >::type cell_names(cell_namesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_milor_pdist_batch(rd_mat, non_zero, nh_n, cell_names, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// az_blas_gemm
NumericMatrix az_blas_gemm(NumericMatrix A, NumericMatrix B, bool transA, bool transB, int threads, CharacterVector dll_paths);
RcppExport SEXP _autozyme_az_blas_gemm(SEXP ASEXP, SEXP BSEXP, SEXP transASEXP, SEXP transBSEXP, SEXP threadsSEXP, SEXP dll_pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    Rcpp::traits::input_parameter< bool >::type transA(transASEXP);
    Rcpp::traits::input_parameter< bool >::type transB(transBSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dll_paths(dll_pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(az_blas_gemm(A, B, transA, transB, threads, dll_paths));
    return rcpp_result_gen;
END_RCPP
}
// az_blas_crossprod
NumericMatrix az_blas_crossprod(NumericMatrix X, int threads, CharacterVector dll_paths);
RcppExport SEXP _autozyme_az_blas_crossprod(SEXP XSEXP, SEXP threadsSEXP, SEXP dll_pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type dll_paths(dll_pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(az_blas_crossprod(X, threads, dll_paths));
    return rcpp_result_gen;
END_RCPP
}
// az_blas_info
List az_blas_info(CharacterVector dll_paths);
RcppExport SEXP _autozyme_az_blas_info(SEXP dll_pathsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type dll_paths(dll_pathsSEXP);
    rcpp_result_gen = Rcpp::wrap(az_blas_info(dll_paths));
    return rcpp_result_gen;
END_RCPP
}
// native_pca_available
bool native_pca_available();
RcppExport SEXP _autozyme_native_pca_available() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(native_pca_available());
    return rcpp_result_gen;
END_RCPP
}
// native_pca_run
List native_pca_run(const arma::mat& X, int npcs, bool weight_by_var);
RcppExport SEXP _autozyme_native_pca_run(SEXP XSEXP, SEXP npcsSEXP, SEXP weight_by_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type npcs(npcsSEXP);
    Rcpp::traits::input_parameter< bool >::type weight_by_var(weight_by_varSEXP);
    rcpp_result_gen = Rcpp::wrap(native_pca_run(X, npcs, weight_by_var));
    return rcpp_result_gen;
END_RCPP
}
// native_cca_formA
arma::mat native_cca_formA(const arma::mat& X1, const arma::mat& X2);
RcppExport SEXP _autozyme_native_cca_formA(SEXP X1SEXP, SEXP X2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X2(X2SEXP);
    rcpp_result_gen = Rcpp::wrap(native_cca_formA(X1, X2));
    return rcpp_result_gen;
END_RCPP
}
// native_matmul
arma::mat native_matmul(const arma::mat& A, const arma::mat& B);
RcppExport SEXP _autozyme_native_matmul(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(native_matmul(A, B));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_row_idx1
NumericVector rctd_cpp_row_idx1(NumericVector y, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_row_idx1(SEXP ySEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_row_idx1(y, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_row_idx_mat
NumericMatrix rctd_cpp_row_idx_mat(NumericMatrix y, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_row_idx_mat(SEXP ySEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_row_idx_mat(y, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_calc_log_l_sum
double rctd_cpp_calc_log_l_sum(NumericVector lambda, NumericVector y, Nullable<NumericVector> row_idx_in, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_calc_log_l_sum(SEXP lambdaSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_calc_log_l_sum(lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_calc_log_l_vec
NumericVector rctd_cpp_calc_log_l_vec(NumericVector lambda, NumericVector y, Nullable<NumericVector> row_idx_in, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_calc_log_l_vec(SEXP lambdaSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_calc_log_l_vec(lambda, y, row_idx_in, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_get_d1_d2
List rctd_cpp_get_d1_d2(NumericVector y, NumericVector lambda, Nullable<NumericVector> row_idx_in, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_get_d1_d2(SEXP ySEXP, SEXP lambdaSEXP, SEXP row_idx_inSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_get_d1_d2(y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_get_der_fast_nonbulk
List rctd_cpp_get_der_fast_nonbulk(NumericMatrix s, NumericVector y, NumericVector lambda, Nullable<NumericVector> row_idx_in, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_get_der_fast_nonbulk(SEXP sSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP row_idx_inSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_get_der_fast_nonbulk(s, y, lambda, row_idx_in, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_solve_wls_p1
NumericVector rctd_cpp_solve_wls_p1(NumericMatrix s, NumericVector y, Nullable<NumericVector> row_idx_in, double initial, double n_umi, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_solve_wls_p1(SEXP sSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP initialSEXP, SEXP n_umiSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< double >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_solve_wls_p1(s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_solve_wls_p2
NumericVector rctd_cpp_solve_wls_p2(NumericMatrix s, NumericVector y, Nullable<NumericVector> row_idx_in, NumericVector initial, double n_umi, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_solve_wls_p2(SEXP sSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP initialSEXP, SEXP n_umiSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_solve_wls_p2(s, y, row_idx_in, initial, n_umi, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_irwls_sparse_p12
List rctd_cpp_irwls_sparse_p12(NumericMatrix s, NumericVector y, Nullable<NumericVector> row_idx_in, double n_umi, int n_iter, double min_change, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_irwls_sparse_p12(SEXP sSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP n_umiSEXP, SEXP n_iterSEXP, SEXP min_changeSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_irwls_sparse_p12(s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_irwls_full_nonbulk
List rctd_cpp_irwls_full_nonbulk(NumericMatrix s, NumericVector y, Nullable<NumericVector> row_idx_in, double n_umi, int n_iter, double min_change, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_irwls_full_nonbulk(SEXP sSEXP, SEXP ySEXP, SEXP row_idx_inSEXP, SEXP n_umiSEXP, SEXP n_iterSEXP, SEXP min_changeSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type s(sSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_irwls_full_nonbulk(s, y, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_score_sparse_candidates
List rctd_cpp_score_sparse_candidates(NumericMatrix profiles, NumericVector y, IntegerVector candidate_cols, Nullable<NumericVector> row_idx_in, double n_umi, double min_change, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_score_sparse_candidates(SEXP profilesSEXP, SEXP ySEXP, SEXP candidate_colsSEXP, SEXP row_idx_inSEXP, SEXP n_umiSEXP, SEXP min_changeSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type profiles(profilesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type candidate_cols(candidate_colsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_score_sparse_candidates(profiles, y, candidate_cols, row_idx_in, n_umi, min_change, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// rctd_cpp_fit_sparse_pair
List rctd_cpp_fit_sparse_pair(NumericMatrix profiles, NumericVector y, IntegerVector pair_cols, Nullable<NumericVector> row_idx_in, double n_umi, int n_iter, double min_change, NumericMatrix q_mat, NumericMatrix sq_mat, NumericVector x_vals, int k_val);
RcppExport SEXP _autozyme_rctd_cpp_fit_sparse_pair(SEXP profilesSEXP, SEXP ySEXP, SEXP pair_colsSEXP, SEXP row_idx_inSEXP, SEXP n_umiSEXP, SEXP n_iterSEXP, SEXP min_changeSEXP, SEXP q_matSEXP, SEXP sq_matSEXP, SEXP x_valsSEXP, SEXP k_valSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type profiles(profilesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pair_cols(pair_colsSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type row_idx_in(row_idx_inSEXP);
    Rcpp::traits::input_parameter< double >::type n_umi(n_umiSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type min_change(min_changeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type q_mat(q_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sq_mat(sq_matSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_vals(x_valsSEXP);
    Rcpp::traits::input_parameter< int >::type k_val(k_valSEXP);
    rcpp_result_gen = Rcpp::wrap(rctd_cpp_fit_sparse_pair(profiles, y, pair_cols, row_idx_in, n_umi, n_iter, min_change, q_mat, sq_mat, x_vals, k_val));
    return rcpp_result_gen;
END_RCPP
}
// score_ligands_cpp
NumericMatrix score_ligands_cpp(NumericMatrix mat, IntegerVector pos_row_idx, IntegerVector neg_row_idx, IntegerVector col_idx, int threads);
RcppExport SEXP _autozyme_score_ligands_cpp(SEXP matSEXP, SEXP pos_row_idxSEXP, SEXP neg_row_idxSEXP, SEXP col_idxSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type pos_row_idx(pos_row_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type neg_row_idx(neg_row_idxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(score_ligands_cpp(mat, pos_row_idx, neg_row_idx, col_idx, threads));
    return rcpp_result_gen;
END_RCPP
}
// fast_lr_outer_triplets_cpp
Rcpp::List fast_lr_outer_triplets_cpp(Rcpp::NumericMatrix a, Rcpp::NumericMatrix b);
RcppExport SEXP _autozyme_fast_lr_outer_triplets_cpp(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_lr_outer_triplets_cpp(a, b));
    return rcpp_result_gen;
END_RCPP
}
// turbo_all_in_one_wilcox
List turbo_all_in_one_wilcox(NumericVector x, IntegerVector p, IntegerVector i, int ncol_orig, int nrow_orig, IntegerVector groups, int ngroups);
RcppExport SEXP _autozyme_turbo_all_in_one_wilcox(SEXP xSEXP, SEXP pSEXP, SEXP iSEXP, SEXP ncol_origSEXP, SEXP nrow_origSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type ncol_orig(ncol_origSEXP);
    Rcpp::traits::input_parameter< int >::type nrow_orig(nrow_origSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_all_in_one_wilcox(x, p, i, ncol_orig, nrow_orig, groups, ngroups));
    return rcpp_result_gen;
END_RCPP
}
// parallel_all_in_one_dgc
List parallel_all_in_one_dgc(SEXP x_sexp, IntegerVector groups, IntegerVector group_sizes);
RcppExport SEXP _autozyme_parallel_all_in_one_dgc(SEXP x_sexpSEXP, SEXP groupsSEXP, SEXP group_sizesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group_sizes(group_sizesSEXP);
    rcpp_result_gen = Rcpp::wrap(parallel_all_in_one_dgc(x_sexp, groups, group_sizes));
    return rcpp_result_gen;
END_RCPP
}
// turbo_annoy_build_search
Rcpp::IntegerMatrix turbo_annoy_build_search(Rcpp::NumericMatrix data, int k, int n_trees, int n_threads);
RcppExport SEXP _autozyme_turbo_annoy_build_search(SEXP dataSEXP, SEXP kSEXP, SEXP n_treesSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_annoy_build_search(data, k, n_trees, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// seurat_exact_knn_f32
Rcpp::IntegerMatrix seurat_exact_knn_f32(Rcpp::NumericMatrix data, int k, int n_threads);
RcppExport SEXP _autozyme_seurat_exact_knn_f32(SEXP dataSEXP, SEXP kSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(seurat_exact_knn_f32(data, k, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// seurat_log_normalize_dgc
void seurat_log_normalize_dgc(S4 mat, double scale_factor, int grain_size);
RcppExport SEXP _autozyme_seurat_log_normalize_dgc(SEXP matSEXP, SEXP scale_factorSEXP, SEXP grain_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type scale_factor(scale_factorSEXP);
    Rcpp::traits::input_parameter< int >::type grain_size(grain_sizeSEXP);
    seurat_log_normalize_dgc(mat, scale_factor, grain_size);
    return R_NilValue;
END_RCPP
}
// az_runumap_knn_cpp
Rcpp::List az_runumap_knn_cpp(Rcpp::NumericMatrix X, int k, int n_trees, int n_iters, int leaf_size, double seed, int n_threads);
RcppExport SEXP _autozyme_az_runumap_knn_cpp(SEXP XSEXP, SEXP kSEXP, SEXP n_treesSEXP, SEXP n_itersSEXP, SEXP leaf_sizeSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type n_trees(n_treesSEXP);
    Rcpp::traits::input_parameter< int >::type n_iters(n_itersSEXP);
    Rcpp::traits::input_parameter< int >::type leaf_size(leaf_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(az_runumap_knn_cpp(X, k, n_trees, n_iters, leaf_size, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// az_runumap_layout_cpp
Rcpp::NumericMatrix az_runumap_layout_cpp(Rcpp::NumericMatrix init, Rcpp::IntegerVector head, Rcpp::IntegerVector tail, Rcpp::NumericVector epochs_per_sample, int n_epochs, double a, double b, double gamma, double initial_alpha, double negative_sample_rate, double seed, int n_threads);
RcppExport SEXP _autozyme_az_runumap_layout_cpp(SEXP initSEXP, SEXP headSEXP, SEXP tailSEXP, SEXP epochs_per_sampleSEXP, SEXP n_epochsSEXP, SEXP aSEXP, SEXP bSEXP, SEXP gammaSEXP, SEXP initial_alphaSEXP, SEXP negative_sample_rateSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type init(initSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type head(headSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type tail(tailSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type epochs_per_sample(epochs_per_sampleSEXP);
    Rcpp::traits::input_parameter< int >::type n_epochs(n_epochsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type initial_alpha(initial_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type negative_sample_rate(negative_sample_rateSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(az_runumap_layout_cpp(init, head, tail, epochs_per_sample, n_epochs, a, b, gamma, initial_alpha, negative_sample_rate, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// turbo_scale_sparse_full
NumericMatrix turbo_scale_sparse_full(S4 sparse_mat, IntegerVector gene_indices, double scale_max);
RcppExport SEXP _autozyme_turbo_scale_sparse_full(SEXP sparse_matSEXP, SEXP gene_indicesSEXP, SEXP scale_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type sparse_mat(sparse_matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gene_indices(gene_indicesSEXP);
    Rcpp::traits::input_parameter< double >::type scale_max(scale_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_scale_sparse_full(sparse_mat, gene_indices, scale_max));
    return rcpp_result_gen;
END_RCPP
}
// turbo_csc_to_csr
List turbo_csc_to_csr(IntegerVector csc_i, IntegerVector csc_p, NumericVector csc_x, int nrow, int ncol);
RcppExport SEXP _autozyme_turbo_csc_to_csr(SEXP csc_iSEXP, SEXP csc_pSEXP, SEXP csc_xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type csc_i(csc_iSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type csc_p(csc_pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type csc_x(csc_xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_csc_to_csr(csc_i, csc_p, csc_x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// turbo_stats_correct_sparse
List turbo_stats_correct_sparse(NumericVector intercepts, NumericVector cell_mu_base, IntegerVector csr_row_ptr, IntegerVector csr_col_idx, NumericVector csr_vals, IntegerVector gene_idx, NumericVector theta, NumericVector corr_factor, double min_var, double clip_lo, double clip_hi, bool do_correct);
RcppExport SEXP _autozyme_turbo_stats_correct_sparse(SEXP interceptsSEXP, SEXP cell_mu_baseSEXP, SEXP csr_row_ptrSEXP, SEXP csr_col_idxSEXP, SEXP csr_valsSEXP, SEXP gene_idxSEXP, SEXP thetaSEXP, SEXP corr_factorSEXP, SEXP min_varSEXP, SEXP clip_loSEXP, SEXP clip_hiSEXP, SEXP do_correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_mu_base(cell_mu_baseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type csr_row_ptr(csr_row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type csr_col_idx(csr_col_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type csr_vals(csr_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gene_idx(gene_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type corr_factor(corr_factorSEXP);
    Rcpp::traits::input_parameter< double >::type min_var(min_varSEXP);
    Rcpp::traits::input_parameter< double >::type clip_lo(clip_loSEXP);
    Rcpp::traits::input_parameter< double >::type clip_hi(clip_hiSEXP);
    Rcpp::traits::input_parameter< bool >::type do_correct(do_correctSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_stats_correct_sparse(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, corr_factor, min_var, clip_lo, clip_hi, do_correct));
    return rcpp_result_gen;
END_RCPP
}
// turbo_fused_resid_center_sparse
NumericMatrix turbo_fused_resid_center_sparse(NumericVector intercepts, NumericVector cell_mu_base, IntegerVector csr_row_ptr, IntegerVector csr_col_idx, NumericVector csr_vals, IntegerVector gene_idx, NumericVector theta, double min_var, double wide_clip_lo, double wide_clip_hi, double narrow_clip_lo, double narrow_clip_hi);
RcppExport SEXP _autozyme_turbo_fused_resid_center_sparse(SEXP interceptsSEXP, SEXP cell_mu_baseSEXP, SEXP csr_row_ptrSEXP, SEXP csr_col_idxSEXP, SEXP csr_valsSEXP, SEXP gene_idxSEXP, SEXP thetaSEXP, SEXP min_varSEXP, SEXP wide_clip_loSEXP, SEXP wide_clip_hiSEXP, SEXP narrow_clip_loSEXP, SEXP narrow_clip_hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type intercepts(interceptsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cell_mu_base(cell_mu_baseSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type csr_row_ptr(csr_row_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type csr_col_idx(csr_col_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type csr_vals(csr_valsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type gene_idx(gene_idxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< double >::type min_var(min_varSEXP);
    Rcpp::traits::input_parameter< double >::type wide_clip_lo(wide_clip_loSEXP);
    Rcpp::traits::input_parameter< double >::type wide_clip_hi(wide_clip_hiSEXP);
    Rcpp::traits::input_parameter< double >::type narrow_clip_lo(narrow_clip_loSEXP);
    Rcpp::traits::input_parameter< double >::type narrow_clip_hi(narrow_clip_hiSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_fused_resid_center_sparse(intercepts, cell_mu_base, csr_row_ptr, csr_col_idx, csr_vals, gene_idx, theta, min_var, wide_clip_lo, wide_clip_hi, narrow_clip_lo, narrow_clip_hi));
    return rcpp_result_gen;
END_RCPP
}
// turbo_FastSparseRowMeanVar
List turbo_FastSparseRowMeanVar(IntegerVector p, IntegerVector i, NumericVector x, int nrow, int ncol);
RcppExport SEXP _autozyme_turbo_FastSparseRowMeanVar(SEXP pSEXP, SEXP iSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_FastSparseRowMeanVar(p, i, x, nrow, ncol));
    return rcpp_result_gen;
END_RCPP
}
// turbo_FastSparseRowVarStd
NumericVector turbo_FastSparseRowVarStd(IntegerVector p, IntegerVector i, NumericVector x, int nrow, int ncol, NumericVector mu, NumericVector sd, double vmax, IntegerVector nnzPerRow);
RcppExport SEXP _autozyme_turbo_FastSparseRowVarStd(SEXP pSEXP, SEXP iSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP muSEXP, SEXP sdSEXP, SEXP vmaxSEXP, SEXP nnzPerRowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< double >::type vmax(vmaxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nnzPerRow(nnzPerRowSEXP);
    rcpp_result_gen = Rcpp::wrap(turbo_FastSparseRowVarStd(p, i, x, nrow, ncol, mu, sd, vmax, nnzPerRow));
    return rcpp_result_gen;
END_RCPP
}
// az_dgc_row_stats_cpp
List az_dgc_row_stats_cpp(SEXP x_sexp, double detected_threshold);
RcppExport SEXP _autozyme_az_dgc_row_stats_cpp(SEXP x_sexpSEXP, SEXP detected_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type detected_threshold(detected_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(az_dgc_row_stats_cpp(x_sexp, detected_threshold));
    return rcpp_result_gen;
END_RCPP
}
// az_dgc_group_summary_cpp
List az_dgc_group_summary_cpp(SEXP x_sexp, IntegerVector groups, int ngroups, double detected_threshold);
RcppExport SEXP _autozyme_az_dgc_group_summary_cpp(SEXP x_sexpSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP, SEXP detected_thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x_sexp(x_sexpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    Rcpp::traits::input_parameter< double >::type detected_threshold(detected_thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(az_dgc_group_summary_cpp(x_sexp, groups, ngroups, detected_threshold));
    return rcpp_result_gen;
END_RCPP
}
// az_dense_group_summary_cpp
List az_dense_group_summary_cpp(NumericMatrix x, IntegerVector groups, int ngroups, double detected_threshold, bool na_rm);
RcppExport SEXP _autozyme_az_dense_group_summary_cpp(SEXP xSEXP, SEXP groupsSEXP, SEXP ngroupsSEXP, SEXP detected_thresholdSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< int >::type ngroups(ngroupsSEXP);
    Rcpp::traits::input_parameter< double >::type detected_threshold(detected_thresholdSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(az_dense_group_summary_cpp(x, groups, ngroups, detected_threshold, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// zyme_soft_assignment
List zyme_soft_assignment(const arma::mat& X, const arma::mat& C, double sigma);
RcppExport SEXP _autozyme_zyme_soft_assignment(SEXP XSEXP, SEXP CSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(zyme_soft_assignment(X, C, sigma));
    return rcpp_result_gen;
END_RCPP
}
// nb_Dd_cpp
List nb_Dd_cpp(NumericVector y, NumericVector mu, double theta_log, NumericVector wt, int level);
RcppExport SEXP _autozyme_nb_Dd_cpp(SEXP ySEXP, SEXP muSEXP, SEXP theta_logSEXP, SEXP wtSEXP, SEXP levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type theta_log(theta_logSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< int >::type level(levelSEXP);
    rcpp_result_gen = Rcpp::wrap(nb_Dd_cpp(y, mu, theta_log, wt, level));
    return rcpp_result_gen;
END_RCPP
}
// nb_dDeta_log_cpp
List nb_dDeta_log_cpp(NumericVector y, NumericVector mu, NumericVector wt, double theta_log, int deriv);
RcppExport SEXP _autozyme_nb_dDeta_log_cpp(SEXP ySEXP, SEXP muSEXP, SEXP wtSEXP, SEXP theta_logSEXP, SEXP derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type theta_log(theta_logSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    rcpp_result_gen = Rcpp::wrap(nb_dDeta_log_cpp(y, mu, wt, theta_log, deriv));
    return rcpp_result_gen;
END_RCPP
}
// linkinv_log_cpp
NumericVector linkinv_log_cpp(NumericVector eta);
RcppExport SEXP _autozyme_linkinv_log_cpp(SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(linkinv_log_cpp(eta));
    return rcpp_result_gen;
END_RCPP
}
// nb_dev_resids_cpp
NumericVector nb_dev_resids_cpp(NumericVector y, NumericVector mu, NumericVector wt, double theta_log);
RcppExport SEXP _autozyme_nb_dev_resids_cpp(SEXP ySEXP, SEXP muSEXP, SEXP wtSEXP, SEXP theta_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type wt(wtSEXP);
    Rcpp::traits::input_parameter< double >::type theta_log(theta_logSEXP);
    rcpp_result_gen = Rcpp::wrap(nb_dev_resids_cpp(y, mu, wt, theta_log));
    return rcpp_result_gen;
END_RCPP
}
// nb_ls_cpp
List nb_ls_cpp(NumericVector y, NumericVector w, double theta_log, double scale);
RcppExport SEXP _autozyme_nb_ls_cpp(SEXP ySEXP, SEXP wSEXP, SEXP theta_logSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type theta_log(theta_logSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(nb_ls_cpp(y, w, theta_log, scale));
    return rcpp_result_gen;
END_RCPP
}
// ucell_fast_scores_dgC
NumericMatrix ucell_fast_scores_dgC(IntegerVector p, IntegerVector i, NumericVector x, int nrow, List pos_list, List neg_list, int maxRank, double w_neg, int int_mat);
RcppExport SEXP _autozyme_ucell_fast_scores_dgC(SEXP pSEXP, SEXP iSEXP, SEXP xSEXP, SEXP nrowSEXP, SEXP pos_listSEXP, SEXP neg_listSEXP, SEXP maxRankSEXP, SEXP w_negSEXP, SEXP int_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type i(iSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< List >::type pos_list(pos_listSEXP);
    Rcpp::traits::input_parameter< List >::type neg_list(neg_listSEXP);
    Rcpp::traits::input_parameter< int >::type maxRank(maxRankSEXP);
    Rcpp::traits::input_parameter< double >::type w_neg(w_negSEXP);
    Rcpp::traits::input_parameter< int >::type int_mat(int_matSEXP);
    rcpp_result_gen = Rcpp::wrap(ucell_fast_scores_dgC(p, i, x, nrow, pos_list, neg_list, maxRank, w_neg, int_mat));
    return rcpp_result_gen;
END_RCPP
}
// accelerate_crossprod
NumericMatrix accelerate_crossprod(NumericMatrix X);
RcppExport SEXP _autozyme_accelerate_crossprod(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(accelerate_crossprod(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_autozyme_fast_iterate_t_impl", (DL_FUNC) &_autozyme_fast_iterate_t_impl, 13},
    {"_autozyme_cpp_aggregate_triMean", (DL_FUNC) &_autozyme_cpp_aggregate_triMean, 3},
    {"_autozyme_cpp_aggregate_triMean_boot", (DL_FUNC) &_autozyme_cpp_aggregate_triMean_boot, 4},
    {"_autozyme_cpp_outer_Pnull", (DL_FUNC) &_autozyme_cpp_outer_Pnull, 8},
    {"_autozyme_cpp_unified_inner", (DL_FUNC) &_autozyme_cpp_unified_inner, 20},
    {"_autozyme_cpp_updateState", (DL_FUNC) &_autozyme_cpp_updateState, 17},
    {"_autozyme_fast_decontXEM_cpp", (DL_FUNC) &_autozyme_fast_decontXEM_cpp, 11},
    {"_autozyme_fitDisp_zyme", (DL_FUNC) &_autozyme_fitDisp_zyme, 15},
    {"_autozyme_row_trimmed_means", (DL_FUNC) &_autozyme_row_trimmed_means, 3},
    {"_autozyme_fitBeta_zyme", (DL_FUNC) &_autozyme_fitBeta_zyme, 13},
    {"_autozyme_fastgam_fit", (DL_FUNC) &_autozyme_fastgam_fit, 10},
    {"_autozyme_calcEsLeBatchCpp", (DL_FUNC) &_autozyme_calcEsLeBatchCpp, 3},
    {"_autozyme_fastFgseaMultilevelBatchCpp", (DL_FUNC) &_autozyme_fastFgseaMultilevelBatchCpp, 8},
    {"_autozyme_count_sum_by_group_dgc", (DL_FUNC) &_autozyme_count_sum_by_group_dgc, 3},
    {"_autozyme_portable_rank_dgc", (DL_FUNC) &_autozyme_portable_rank_dgc, 3},
    {"_autozyme_rank_sum_by_group_dgc", (DL_FUNC) &_autozyme_rank_sum_by_group_dgc, 3},
    {"_autozyme_omp_sum_nnz_expm1_groups", (DL_FUNC) &_autozyme_omp_sum_nnz_expm1_groups, 4},
    {"_autozyme_omp_filter_pct_lfc", (DL_FUNC) &_autozyme_omp_filter_pct_lfc, 13},
    {"_autozyme_omp_subset_transpose_rank_pval", (DL_FUNC) &_autozyme_omp_subset_transpose_rank_pval, 6},
    {"_autozyme_omp_rank_ustat_pval", (DL_FUNC) &_autozyme_omp_rank_ustat_pval, 5},
    {"_autozyme_fast_smooth_window_cpp", (DL_FUNC) &_autozyme_fast_smooth_window_cpp, 2},
    {"_autozyme_fast_smooth_long_chromosomes_cpp", (DL_FUNC) &_autozyme_fast_smooth_long_chromosomes_cpp, 4},
    {"_autozyme_fast_scale_columns_cpp", (DL_FUNC) &_autozyme_fast_scale_columns_cpp, 2},
    {"_autozyme_fast_log1p_scale_cpp", (DL_FUNC) &_autozyme_fast_log1p_scale_cpp, 2},
    {"_autozyme_fast_invert_log2_cpp", (DL_FUNC) &_autozyme_fast_invert_log2_cpp, 2},
    {"_autozyme_fast_center_columns_cpp", (DL_FUNC) &_autozyme_fast_center_columns_cpp, 2},
    {"_autozyme_fast_subtract_ref_bounds_cpp", (DL_FUNC) &_autozyme_fast_subtract_ref_bounds_cpp, 5},
    {"_autozyme_fast_apply_dropout_cpp", (DL_FUNC) &_autozyme_fast_apply_dropout_cpp, 2},
    {"_autozyme_fast_state_consensus_cpp", (DL_FUNC) &_autozyme_fast_state_consensus_cpp, 1},
    {"_autozyme_fast_cell_prob_cpp", (DL_FUNC) &_autozyme_fast_cell_prob_cpp, 2},
    {"_autozyme_fast_viterbi_adj_cpp", (DL_FUNC) &_autozyme_fast_viterbi_adj_cpp, 5},
    {"_autozyme_zyme_fill_dcast", (DL_FUNC) &_autozyme_zyme_fill_dcast, 5},
    {"_autozyme_fast_milor_pdist_one", (DL_FUNC) &_autozyme_fast_milor_pdist_one, 2},
    {"_autozyme_fast_milor_pdist_batch", (DL_FUNC) &_autozyme_fast_milor_pdist_batch, 5},
    {"_autozyme_az_blas_gemm", (DL_FUNC) &_autozyme_az_blas_gemm, 6},
    {"_autozyme_az_blas_crossprod", (DL_FUNC) &_autozyme_az_blas_crossprod, 3},
    {"_autozyme_az_blas_info", (DL_FUNC) &_autozyme_az_blas_info, 1},
    {"_autozyme_native_pca_available", (DL_FUNC) &_autozyme_native_pca_available, 0},
    {"_autozyme_native_pca_run", (DL_FUNC) &_autozyme_native_pca_run, 3},
    {"_autozyme_native_cca_formA", (DL_FUNC) &_autozyme_native_cca_formA, 2},
    {"_autozyme_native_matmul", (DL_FUNC) &_autozyme_native_matmul, 2},
    {"_autozyme_rctd_cpp_row_idx1", (DL_FUNC) &_autozyme_rctd_cpp_row_idx1, 2},
    {"_autozyme_rctd_cpp_row_idx_mat", (DL_FUNC) &_autozyme_rctd_cpp_row_idx_mat, 2},
    {"_autozyme_rctd_cpp_calc_log_l_sum", (DL_FUNC) &_autozyme_rctd_cpp_calc_log_l_sum, 7},
    {"_autozyme_rctd_cpp_calc_log_l_vec", (DL_FUNC) &_autozyme_rctd_cpp_calc_log_l_vec, 7},
    {"_autozyme_rctd_cpp_get_d1_d2", (DL_FUNC) &_autozyme_rctd_cpp_get_d1_d2, 7},
    {"_autozyme_rctd_cpp_get_der_fast_nonbulk", (DL_FUNC) &_autozyme_rctd_cpp_get_der_fast_nonbulk, 8},
    {"_autozyme_rctd_cpp_solve_wls_p1", (DL_FUNC) &_autozyme_rctd_cpp_solve_wls_p1, 9},
    {"_autozyme_rctd_cpp_solve_wls_p2", (DL_FUNC) &_autozyme_rctd_cpp_solve_wls_p2, 9},
    {"_autozyme_rctd_cpp_irwls_sparse_p12", (DL_FUNC) &_autozyme_rctd_cpp_irwls_sparse_p12, 10},
    {"_autozyme_rctd_cpp_irwls_full_nonbulk", (DL_FUNC) &_autozyme_rctd_cpp_irwls_full_nonbulk, 10},
    {"_autozyme_rctd_cpp_score_sparse_candidates", (DL_FUNC) &_autozyme_rctd_cpp_score_sparse_candidates, 10},
    {"_autozyme_rctd_cpp_fit_sparse_pair", (DL_FUNC) &_autozyme_rctd_cpp_fit_sparse_pair, 11},
    {"_autozyme_score_ligands_cpp", (DL_FUNC) &_autozyme_score_ligands_cpp, 5},
    {"_autozyme_fast_lr_outer_triplets_cpp", (DL_FUNC) &_autozyme_fast_lr_outer_triplets_cpp, 2},
    {"_autozyme_turbo_all_in_one_wilcox", (DL_FUNC) &_autozyme_turbo_all_in_one_wilcox, 7},
    {"_autozyme_parallel_all_in_one_dgc", (DL_FUNC) &_autozyme_parallel_all_in_one_dgc, 3},
    {"_autozyme_turbo_annoy_build_search", (DL_FUNC) &_autozyme_turbo_annoy_build_search, 4},
    {"_autozyme_seurat_exact_knn_f32", (DL_FUNC) &_autozyme_seurat_exact_knn_f32, 3},
    {"_autozyme_seurat_log_normalize_dgc", (DL_FUNC) &_autozyme_seurat_log_normalize_dgc, 3},
    {"_autozyme_az_runumap_knn_cpp", (DL_FUNC) &_autozyme_az_runumap_knn_cpp, 7},
    {"_autozyme_az_runumap_layout_cpp", (DL_FUNC) &_autozyme_az_runumap_layout_cpp, 12},
    {"_autozyme_turbo_scale_sparse_full", (DL_FUNC) &_autozyme_turbo_scale_sparse_full, 3},
    {"_autozyme_turbo_csc_to_csr", (DL_FUNC) &_autozyme_turbo_csc_to_csr, 5},
    {"_autozyme_turbo_stats_correct_sparse", (DL_FUNC) &_autozyme_turbo_stats_correct_sparse, 12},
    {"_autozyme_turbo_fused_resid_center_sparse", (DL_FUNC) &_autozyme_turbo_fused_resid_center_sparse, 12},
    {"_autozyme_turbo_FastSparseRowMeanVar", (DL_FUNC) &_autozyme_turbo_FastSparseRowMeanVar, 5},
    {"_autozyme_turbo_FastSparseRowVarStd", (DL_FUNC) &_autozyme_turbo_FastSparseRowVarStd, 9},
    {"_autozyme_az_dgc_row_stats_cpp", (DL_FUNC) &_autozyme_az_dgc_row_stats_cpp, 2},
    {"_autozyme_az_dgc_group_summary_cpp", (DL_FUNC) &_autozyme_az_dgc_group_summary_cpp, 4},
    {"_autozyme_az_dense_group_summary_cpp", (DL_FUNC) &_autozyme_az_dense_group_summary_cpp, 5},
    {"_autozyme_zyme_soft_assignment", (DL_FUNC) &_autozyme_zyme_soft_assignment, 3},
    {"_autozyme_nb_Dd_cpp", (DL_FUNC) &_autozyme_nb_Dd_cpp, 5},
    {"_autozyme_nb_dDeta_log_cpp", (DL_FUNC) &_autozyme_nb_dDeta_log_cpp, 5},
    {"_autozyme_linkinv_log_cpp", (DL_FUNC) &_autozyme_linkinv_log_cpp, 1},
    {"_autozyme_nb_dev_resids_cpp", (DL_FUNC) &_autozyme_nb_dev_resids_cpp, 4},
    {"_autozyme_nb_ls_cpp", (DL_FUNC) &_autozyme_nb_ls_cpp, 4},
    {"_autozyme_ucell_fast_scores_dgC", (DL_FUNC) &_autozyme_ucell_fast_scores_dgC, 9},
    {"_autozyme_accelerate_crossprod", (DL_FUNC) &_autozyme_accelerate_crossprod, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_autozyme(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
